service: lambda-sample-java

provider:
  name: aws
  runtime: java11
  tracing:
    lambda: true
    apiGateway: true
  region: sa-east-1
  memorySize: 2048
  timeout: 120

package:
  artifact: build/distributions/hello.zip

functions:
  helloJava11:
    handler: com.datadog.lambda.sample.java.Handler
    # Define function environment variables here
    environment:
      JAVA_TOOL_OPTIONS: -javaagent:"/opt/java/lib/dd-java-agent.jar"
      DD_LOGS_INJECTION: true
      DD_JMXFETCH_ENABLED: false
      DD_TRACE_ENABLED: true
      DD_LOG_LEVEL: debug
    layers:
      - arn:aws:lambda:sa-east-1:464622532012:layer:dd-trace-java:3
    events:
      - http:
          path: helloDog
          method: get
